# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vdss_pb2 as vdss__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vdss_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VDSSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertVector = channel.unary_unary(
                '/vdss.VDSSService/UpsertVector',
                request_serializer=vdss__pb2.UpsertVectorRequest.SerializeToString,
                response_deserializer=vdss__pb2.UpsertVectorResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/vdss.VDSSService/Search',
                request_serializer=vdss__pb2.SearchRequest.SerializeToString,
                response_deserializer=vdss__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.DeleteVector = channel.unary_unary(
                '/vdss.VDSSService/DeleteVector',
                request_serializer=vdss__pb2.DeleteVectorRequest.SerializeToString,
                response_deserializer=vdss__pb2.DeleteVectorResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/vdss.VDSSService/CreateCollection',
                request_serializer=vdss__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=vdss__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.Flush = channel.unary_unary(
                '/vdss.VDSSService/Flush',
                request_serializer=vdss__pb2.FlushRequest.SerializeToString,
                response_deserializer=vdss__pb2.FlushResponse.FromString,
                _registered_method=True)


class VDSSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpsertVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Flush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VDSSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertVector': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertVector,
                    request_deserializer=vdss__pb2.UpsertVectorRequest.FromString,
                    response_serializer=vdss__pb2.UpsertVectorResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vdss__pb2.SearchRequest.FromString,
                    response_serializer=vdss__pb2.SearchResponse.SerializeToString,
            ),
            'DeleteVector': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVector,
                    request_deserializer=vdss__pb2.DeleteVectorRequest.FromString,
                    response_serializer=vdss__pb2.DeleteVectorResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=vdss__pb2.CreateCollectionRequest.FromString,
                    response_serializer=vdss__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=vdss__pb2.FlushRequest.FromString,
                    response_serializer=vdss__pb2.FlushResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vdss.VDSSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vdss.VDSSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VDSSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpsertVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vdss.VDSSService/UpsertVector',
            vdss__pb2.UpsertVectorRequest.SerializeToString,
            vdss__pb2.UpsertVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vdss.VDSSService/Search',
            vdss__pb2.SearchRequest.SerializeToString,
            vdss__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vdss.VDSSService/DeleteVector',
            vdss__pb2.DeleteVectorRequest.SerializeToString,
            vdss__pb2.DeleteVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vdss.VDSSService/CreateCollection',
            vdss__pb2.CreateCollectionRequest.SerializeToString,
            vdss__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vdss.VDSSService/Flush',
            vdss__pb2.FlushRequest.SerializeToString,
            vdss__pb2.FlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
